### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by cryo75** [Tavenem/Blazor.ImageEditor#1]
Is this project still active?

**Comment by JoshBuilt** [comment]
It does not appear to be.  I've altered it fairly extensively in a project I'm working on, however.  What's your use case?  If it sounds like it coincides with mine, I might fork the repo and push my version.

**Comment by cryo75** [comment]
I newd to be able to zoom in/out of the image, have a rectangle at a fix3d aspect ratio moved around the image and then crop that area.

**Comment by jusovsky** [comment]
I needed the zoom and panning functionality as well, and implemented it using mouse wheel and middle mouse drag, respectively.  I have not been able to integrate touch, as this requires a special build of Fabric.js and I have not been able to successfully integrate that.  I should have some time next week to try to create a fork of this project and get my changes uploaded.  Hopefully you'll find them useful.

**Comment by cryo75** [comment]
Thanks.

**Comment by WilStead** [comment]
This project is not being actively maintained, but it hasn't been abandoned and pull requests would certainly be welcome.

My newer [Tavenem.Blazor.Framework](https://github.com/Tavenem/Blazor.Framework) project has an [Image Editor control](https://tavenem.com/Blazor.Framework/components/image-editor) which is very different from this one, but cropping is supported and the UI is significantly improved over this control.

**Comment by cryo75** [comment]
Is it based only on Bootstrap and nothing else?

**Comment by WilStead** [comment]
No, it isn't based on Bootstrap. I might not be understanding the question correctly, but the image editor in the Tavenem.Blazor.Framework library [(docs here)](https://tavenem.com/Blazor.Framework/) is based on [PixiJS](https://pixijs.com/), rather than [Fabric.js](http://fabricjs.com/) like this one.

**Comment by cryo75** [comment]
That's good. The less dependwncies the better. I looked at the framework and it has all thw components I had to build myself!

**Comment by WilStead** [comment]
I'm glad to hear it looks helpful. That project _is_ being actively maintained. It gets regular updates for bugfixes and feature improvements. The image editor in particular was given a number of improvements recently.

I'll close this issue for now since it seems like the original question has been answered. If @JoshBuilt or @jusovsky would like to submit PRs with any updates to this project, I'd be happy to review and merge them as soon as possible.

**Comment by nhwilly** [comment]
Oops.  Had high hopes for this one.  Documentation is actually good.  

I'll check out the `Framework`, but I'm already knee deep in MudBlazor.

Good luck, @WilStead
